### ISSUE TITLE
Loading "Salesforce Reference: LWC and Aura Component Library (EXPERIMENTAL)" does not work

### ISSUE THREAD

**Issue by RupertBarrow** [Oblongmana/vscode-salesforce-doc-lookup#11]
Error message says : 
"Unexpected error while trying to access Salesforce doc. Please log an issue and repro steps at https://github.com/Oblongmana/vscode-salesforce-doc-lookup/issues"

**Comment by RupertBarrow** [comment]
error message in console : 


No existing extension version, current version is 1.3.1
Extension version changed. Detected Apex Cache out of date after Salesforce relocated Reference doc. Force-clearing Apex Reference cache.
Extension version changed: prior was <=1.3.0. Invalidating all caches to support update that allows Breadcrumb searching.
Unexpected Error: ParseError: Unexpected token * in JSON at position 0 in "https://developer.salesforce.com/docs/component-library/aura"RequestError: Unexpected token * in JSON at position 0 in "https://developer.salesforce.com/docs/component-library/aura"
    at Object.parseBody [as default] (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/parse-body.js:22:15)
    at /Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/index.js:158:40
    at JSON.parse (<anonymous>)
    at parseJson (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/index.js:118:35)
    at Object.parseBody [as default] (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/parse-body.js:11:48)
    at /Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/index.js:158:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Unexpected Error: ParseError: Unexpected token * in JSON at position 0 in "https://developer.salesforce.com/docs/component-library/aura"RequestError: Unexpected token * in JSON at position 0 in "https://developer.salesforce.com/docs/component-library/aura"
    at Object.parseBody [as default] (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/parse-body.js:22:15)
    at /Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/index.js:158:40
    at JSON.parse (<anonymous>)
    at parseJson (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/index.js:118:35)
    at Object.parseBody [as default] (/Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/parse-body.js:11:48)
    at /Users/xxxxx/.vscode/extensions/oblongmana.vscode-salesforce-doc-lookup-1.3.1/node_modules/got/dist/source/as-promise/index.js:158:40
    at processTicksAndRejections (node:internal/process/task_queues:96:5)

**Comment by Oblongmana** [comment]
Kia ora @RupertBarrow, thanks for the report, and including the console detail! 

Looks like Salesforce have made some updates, will have to investigate what's changed and if we can still get a table of contents out of there. Will investigate this weekend 🕵️‍♂️

**Comment by Oblongmana** [comment]
Good news! Just looks like a change to the fwuid/"Framework Unique ID" on the SF doc for Aura/LWC components, something I suspected might change periodically. 

Just testing the upgrade process now - will invalidate old local cached doc entries and include the new FWUID in new queries. Should have an update out shortly.

**Comment by Oblongmana** [comment]
@RupertBarrow Minor hiccup in publishing a new version so it's had two patch version bumps - once you've updated to the latest `1.3.3` you should find this documentation is working again!

Closing the ticket as resolved, but please do let me know if you run into any further issues. Thanks again for reporting this 🙏

**Comment by RupertBarrow** [comment]
Works great, thanks !
